version: "3"

services:
    webapp:
        build:
            context: .
            dockerfile: docker/webapp/dev.dockerfile

        container_name: "webapp_react"
        ports:
            - "3000:3000"

