export const constants = {
    logoText: '>_ TIPS & TRICKS',
    appName: 'TIPS & TRICKS',
    catchPhrasePrimary: 'Your development tips are worth gold !',
    catchPhraseSecondary: 'Join our community and share your favorite commands with developers from around the world. 🔒💡',
    infosRegisterPassword: 'The password must be at least 12 characters long, contain at least one uppercase letter, one digit, and one special character.',
    passwordBadFormat: 'The password does not have the correct format.',
    passwordNotSame: 'The passwords do not match.',
    usernameMinChar: 'The username must be at least two characters long.',
    emailBadFormat: 'The email does not have the correct format.',
    usernameAlreadyUsed: 'This username is already taken, please choose another one.',
    emailAlreadyUsed: 'This email is already taken.',
    unknownError: 'Unknown error, please try again later.',
    badCredentials: 'Bad credentials !',
    accountCreateSuccess: 'Your account has been successfully created ! Please log in.',
    copyTipsToTipsBoard: "Would you want to save this tips ?",
    modalTitleRequired: "Title is required.",
    modalCommandRequired: "Command is required.",
}